import shutil
wait (3)
click("gedit-btnNew.png")
wait (2)
click("gedit-btnOpen.png")
wait("dlgOpenFiles.png",FOREVER)
click("dlgOpenFiles-tbtnroot.png")
wait (5)
click("dlgOpenFiles-btnCancel.png")
waitVanish("dlgOpenFiles.png",FOREVER)
